[package]
name = "liniya"
version = "0.1.0"
authors = ["mason"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ncollide3d = "*"
bvh = "0.3"
nalgebra = "0.26"
anyhow = "*"
thiserror = "*"
